# File: docker-compose.yml
version: '3.8'

services:
  backend:
    build: ./backend
    container_name: school-backend
    restart: unless-stopped
    env_file: ./backend/.env
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules # Use container's node_modules
    networks:
      - school-network
    depends_on:
      - mysql_db

  frontend:
    build: ./frontend
    container_name: school-frontend
    restart: unless-stopped
    ports:
      - "3000:80" # Nginx serves on port 80 inside the container
    volumes:
      - ./frontend:/app
      - /app/node_modules # Use container's node_modules
    networks:
      - school-network
    depends_on:
      - backend

  mysql_db:
    image: mysql:8.0
    container_name: school-mysql
    restart: unless-stopped
    env_file: ./backend/.env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3307:3306" # Connect locally on 3307 if needed
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - school-network

networks:
  school-network:
    driver: bridge

volumes:
  mysql-data: